/*Tworzenie tabel*/

CREATE TABLE osoby 
   (imie VARCHAR2(10),
   email VARCHAR2(60));
   
/

CREATE TABLE zabronionePary
(imie VARCHAR2(10),
zabronione VARCHAR2(10))

/

CREATE TABLE wynikLosowania 
( numer NUMBER(2),
imie VARCHAR2(10),
wylosowany VARCHAR2(10))

/

INSERT INTO zabronionePary (imie, zabronione)
SELECT 'ADAM', 'EWA' FROM DUAL
UNION ALL SELECT 'EWA', 'ADAM' FROM DUAL 
UNION ALL SELECT 'ANIA', 'RADEK' FROM DUAL 
UNION ALL SELECT 'RADEK', 'ANIA' FROM DUAL 
UNION ALL SELECT 'KAMIL', 'JULITA' FROM DUAL 
UNION ALL SELECT 'JULITA', 'KAMIL' FROM DUAL 
UNION ALL SELECT 'GRZEGORZ', 'MAGDA' FROM DUAL 
UNION ALL SELECT 'MAGDA', 'GRZEGORZ' FROM DUAL 


/

INSERT INTO osoby (imie)
SELECT 'ADAM' FROM DUAL
UNION ALL SELECT 'EWA' FROM DUAL 
UNION ALL SELECT 'ANIA' FROM DUAL 
UNION ALL SELECT 'RADEK' FROM DUAL 
UNION ALL SELECT 'KAMIL' FROM DUAL 
UNION ALL SELECT 'JULITA' FROM DUAL 
UNION ALL SELECT 'GRZEGORZ' FROM DUAL 
UNION ALL SELECT 'MAGDA' FROM DUAL 